[package]
name = "battery-demo-2"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-backtrace = { version = "0.18.1", features = [
    "esp32c6",
    "panic-handler",
    "println",
] }
esp-hal = { version = "1.0.0", features = ["esp32c6", "unstable"] }
esp-println = { version = "0.16.1", features = ["esp32c6", "log-04"] }
log = { version = "0.4.29" }
esp-alloc = { version = "0.9.0" }
embedded-io = "0.7.1"
heapless = { version = "0.9.2", default-features = false }
embassy-executor = { version = "0.9.1" }
embassy-time = { version = "0.5.0" }
esp-rtos = { version = "0.2.0", features = ["embassy", "esp32c6", "log-04", "esp-alloc"]}
static_cell = "2.1.1"
rand_core = "0.9.5"
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
esp-sync = { version = "0.1.1", features = ["esp32c6", "log-04"] }

# TODO: Really we'd only like these to run for the Device target.
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false